language: php

sudo: required

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - coverage=no
  matrix:
    - setup=basic
    - setup=stable

addons:
   chrome: stable

services:
  - xvfb

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true
  - php ./create-sqlite-db
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "satooshi/php-coveralls=^2.1" --prefer-dist --no-interaction --dev; fi
  - ./vendor/bin/dusk-updater update
  - export DISPLAY=:99.0
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

script:
  - if [[ $coverage = 'yes' ]]; then ./vendor/bin/phpunit -c ./ --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit -c ./ --testdox --verbose; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/php-coveralls -v; fi

matrix:
  include:
    - php: 7.1
      env: setup=coveralls coverage=yes
  allow_failures:
    - env: setup=coveralls coverage=yes
  fast_finish: true
