language: php

sudo: required

php:
  - 7.3

addons:
   chrome: stable

services:
  - xvfb

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true
  - php ./create-sqlite-db
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

before_script:
  - composer install --prefer-dist --no-interaction
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - ./vendor/bin/dusk-updater detect --auto-update
  - ./testbench-dusk package:discover
  - export DISPLAY=:99.0
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

script:
  - CI=true ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php-coveralls.phar -v

matrix:
  fast_finish: true
