name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php:
          - "7.2"
          - "7.3"
          - "7.4"
        dependencies:
          - "locked"
          - "highest"
          - "lowest"
        experimental:
          - false
        include:
          - php: "8.0"
            dependencies: "locked"
            experimental: true
          - php: "8.0"
            dependencies: "highest"
            experimental: true
          - php: "8.0"
            dependencies: "lowest"
            experimental: true

    name: PHP${{ matrix.php }} on ubuntu-latest (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-cache"
      - name: Create database
        run: php ./create-sqlite-db
      - name: Upgrade Chrome Driver
        run: vendor/bin/dusk-updater detect --auto-update
      - name: Start Chrome Driver
        run: vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Execute tests
        run: vendor/bin/phpunit
